### ISSUE TITLE
police still can't drive police cars

### ISSUE THREAD

**Issue by radiodrag** [esx-community/ESX-Snippet#15]
I took the latest "fixed" code but still doesn't works

![image](https://user-images.githubusercontent.com/10645568/48931600-477ad380-eec5-11e8-99c0-a5779054d6db.png)
![image](https://user-images.githubusercontent.com/10645568/48931607-55c8ef80-eec5-11e8-9085-d14a0d8243e1.png)

**Comment by CubeTroy** [comment]
up
